"""OpenAI-backed ``AiProvider`` implementation.

Talks to the OpenAI Chat Completions REST API directly via ``httpx`` — no
``openai`` SDK dependency is introduced.
"""

from __future__ import annotations

import logging

import httpx

from app.ai.exceptions import AiConfigurationError, AiProviderError
from app.ai.interfaces import AiCompletion
from app.utils.retry import RetryPolicy, retry_call

__all__ = ["OpenAiProvider"]

logger = logging.getLogger(__name__)

_DEFAULT_BASE_URL = "https://api.openai.com/v1"

#: Transient failure types eligible for retry. Excludes 4xx-mapped
#: ``httpx.HTTPStatusError`` (raised only for non-retryable statuses — see
#: ``_post``) so an authentication or validation failure is never retried.
_RETRYABLE_EXCEPTIONS: tuple[type[BaseException], ...] = (
    httpx.TimeoutException,
    httpx.ConnectError,
    httpx.ReadError,
    httpx.RemoteProtocolError,
)

#: HTTP status codes worth retrying — server-side/rate-limit failures that
#: may succeed on a subsequent attempt. Every other non-2xx status is
#: treated as permanent and fails immediately.
_RETRYABLE_STATUS_CODES = frozenset({429, 500, 502, 503, 504})


class _RetryableStatusError(Exception):
    """Internal signal that a response's status code warrants a retry."""


class OpenAiProvider:
    """An ``AiProvider`` implementation backed by the OpenAI Chat Completions API."""

    def __init__(
        self,
        *,
        api_key: str,
        model: str,
        timeout_seconds: float,
        base_url: str = _DEFAULT_BASE_URL,
        provider_name: str = "openai",
        retry_policy: RetryPolicy | None = None,
        transport: httpx.BaseTransport | None = None,
    ) -> None:
        """Initialize the provider with injected configuration.

        Args:
            api_key: The OpenAI (or OpenAI-compatible) API key. Never
                hardcoded — sourced from
                ``app.config.settings.AiSettings.api_key``.
            model: The model identifier to request (e.g. an operator-
                configured ``AI_MODEL`` value).
            timeout_seconds: The request timeout applied to every call.
            base_url: The API base URL, overridable for testing or for
                an OpenAI-compatible third-party API (e.g. Groq).
            provider_name: The label recorded on every ``AiCompletion``/
                ``AiProviderError`` this instance produces. Defaults to
                ``"openai"``; ``app.bootstrap._build_ai_provider`` passes
                ``"groq"`` when this class is reused for Groq's
                wire-compatible API, so the UI's "generated by" label and
                error logs correctly reflect which vendor actually served
                the request rather than always claiming OpenAI.
            retry_policy: The retry policy governing transient-failure
                retries. Defaults to a policy scoped to network-level and
                ``_RETRYABLE_STATUS_CODES`` failures only.
            transport: An ``httpx`` transport override, for tests
                (``httpx.MockTransport``) — never set in production.

        Raises:
            AiConfigurationError: If ``api_key`` or ``model`` is blank.
        """
        if not api_key.strip():
            raise AiConfigurationError("Cannot construct an OpenAiProvider: api_key is blank.")
        if not model.strip():
            raise AiConfigurationError("Cannot construct an OpenAiProvider: model is blank.")

        self._model = model
        self._provider_name = provider_name
        self._client = httpx.Client(
            base_url=base_url,
            timeout=timeout_seconds,
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
            transport=transport,
        )
        self._retry_policy = retry_policy or RetryPolicy(
            max_attempts=3,
            base_delay_seconds=0.5,
            backoff_multiplier=2.0,
            max_delay_seconds=5.0,
            jitter=True,
            retryable_exceptions=(*_RETRYABLE_EXCEPTIONS, _RetryableStatusError),
        )
        self._logger = logging.getLogger(f"{__name__}.OpenAiProvider")

    def complete(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
        max_output_tokens: int = 600,
        temperature: float = 0.2,
    ) -> AiCompletion:
        """Generate a single completion via the OpenAI Chat Completions API.

        Raises:
            AiProviderError: If the call fails after any configured retry
                is exhausted, or the response cannot be parsed.
        """
        payload = {
            "model": self._model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "max_tokens": max_output_tokens,
            "temperature": temperature,
        }

        try:
            response = retry_call(
                lambda: self._post_once(payload), policy=self._retry_policy
            )
        except Exception as exc:  # noqa: BLE001 - translated into a typed error below
            self._logger.warning(
                "%s completion request failed: %s", self._provider_name, exc, exc_info=exc
            )
            raise AiProviderError(self._provider_name, str(exc)) from exc

        try:
            body = response.json()
            text = body["choices"][0]["message"]["content"]
        except (KeyError, IndexError, ValueError) as exc:
            raise AiProviderError(self._provider_name, f"unparsable response: {exc}") from exc

        return AiCompletion(text=text, provider_name=self._provider_name, model=self._model)

    def _post_once(self, payload: dict) -> httpx.Response:
        """Perform a single completion request attempt.

        Raises:
            _RetryableStatusError: If the response's status code is in
                ``_RETRYABLE_STATUS_CODES``.
            httpx.HTTPStatusError: If the response is a non-retryable
                error status.
        """
        response = self._client.post("/chat/completions", json=payload)
        if response.status_code in _RETRYABLE_STATUS_CODES:
            raise _RetryableStatusError(f"HTTP {response.status_code}: {response.text[:200]}")
        response.raise_for_status()
        return response
