"""Identifier generation utilities.

Per the Database Schema Design Document (DSD Section 1.6), every
*persisted row's* primary key is generated by PostgreSQL itself, via the
``pgcrypto`` extension's ``gen_random_uuid()`` function — no repository,
service, or utility in this codebase constructs a primary key in Python.

This module exists for the identifiers the architecture documents
describe as being generated by *application* code rather than the
database: request-correlation identifiers surfaced in every API
response's ``meta.request_id`` and structured log line (API-ADD Section
9, Section 27), and general-purpose UUIDs needed outside the context of
a database insert (for example, constructing test fixtures, per TSD
Section 11, or a client-side temporary key for an optimistic UI update
that has not yet been persisted).
"""

from __future__ import annotations

import uuid

__all__ = [
    "generate_uuid",
    "generate_uuid_str",
    "generate_request_correlation_id",
]

#: The fixed prefix used for every generated request-correlation
#: identifier, matching the example values shown throughout the API
#: Design Document (e.g. ``"req_8f2c1a90"``, API-ADD Section 9).
_REQUEST_ID_PREFIX = "req_"

#: The number of hex characters retained from a UUID4's hex
#: representation when building a request-correlation identifier —
#: short enough to be convenient in logs, long enough to make an
#: accidental collision within a single deployment's log retention
#: window negligible.
_REQUEST_ID_SUFFIX_LENGTH = 8


def generate_uuid() -> uuid.UUID:
    """Generate a new random (version 4) UUID.

    This function is not used to generate a value that will become a
    table's primary key — per DSD Section 1.6, that generation always
    happens in PostgreSQL. It is provided for the narrower set of cases
    described in this module's docstring where an application-generated
    UUID is legitimately needed.

    Returns:
        A new, randomly generated UUID.
    """
    return uuid.uuid4()


def generate_uuid_str() -> str:
    """Generate a new random UUID and return its canonical string form.

    The returned string matches API-ADD Section 3.8's canonical UUID
    format: lowercase, hyphenated.

    Returns:
        The canonical lowercase, hyphenated string representation of a
        new UUID4.
    """
    return str(generate_uuid())


def generate_request_correlation_id() -> str:
    """Generate a new request-correlation identifier.

    Used to populate ``meta.request_id`` on an API response (API-ADD
    Section 9) and the corresponding structured log entry (API-ADD
    Section 27) when the caller did not supply an ``X-Request-Id`` header
    of their own to echo back instead.

    Returns:
        A correlation identifier of the form ``"req_"`` followed by
        eight lowercase hexadecimal characters, e.g. ``"req_8f2c1a90"``.
    """
    return f"{_REQUEST_ID_PREFIX}{uuid.uuid4().hex[:_REQUEST_ID_SUFFIX_LENGTH]}"
