"""The Reminder Dispatch job.

Per WEDD Section 8.3, this job discovers pending workflow stages nearing
(but not yet past) their escalation threshold and enqueues a
``send_reminder`` job (via ``JobDispatcher``) for each one, avoiding
sending a duplicate reminder to the same recipient for the same request
within a configurable cooldown window. Per this package's design brief,
this job never constructs or persists a notification directly — every
actual notification is generated by
``app.jobs.handlers.handle_send_reminder`` (via
``NotificationService.notify_reminder``), now executed by a worker
process (or, when Redis is not configured, synchronously by
``JobDispatcher``'s in-process fallback).
"""

from __future__ import annotations

import logging
from uuid import UUID

from app.database.repositories.approval_repository import ApprovalRepository
from app.database.repositories.base_repository import Page
from app.database.repositories.notification_repository import NotificationRepository
from app.database.repositories.request_repository import RequestRepository
from app.database.repositories.workflow_repository import (
    WorkflowDefinitionRepository,
    WorkflowStageRecord,
)
from app.jobs.job_service import JobDispatcher
from app.jobs.task_types import TASK_SEND_REMINDER
from app.models import WorkflowDefinition
from app.models.enums import JobPriority, NotificationType
from app.scheduler.interfaces import ExecutionContext
from app.scheduler.jobs import BaseJob, iter_pending_stages, load_stage_context, run_over_items
from app.utils.datetime_utils import format_iso8601, seconds_between, utc_now
from app.workflow.engine import WorkflowEngine

__all__ = ["ReminderJob"]

#: The number of most-recent notifications to inspect, per recipient,
#: when checking for a duplicate reminder. Bounded to keep the
#: duplicate-avoidance check cheap; a recipient's most recent
#: notifications are by far the most likely place a prior reminder for
#: the same request would appear.
_DUPLICATE_CHECK_PAGE_SIZE = 50

#: A reminder is best-effort and already has its own dedup/cooldown
#: tolerance — a smaller attempt budget than the system-wide default is
#: deliberate.
_SEND_REMINDER_MAX_ATTEMPTS = 3


class ReminderJob(BaseJob):
    """Sends reminder notifications for pending stages nearing their escalation threshold."""

    def __init__(
        self,
        *,
        job_dispatcher: JobDispatcher,
        approval_repo: ApprovalRepository,
        request_repo: RequestRepository,
        workflow_definition_repo: WorkflowDefinitionRepository,
        notification_repo: NotificationRepository,
        workflow_engine: WorkflowEngine,
        interval_seconds: int = 86400,
        lead_time_hours: float = 4.0,
        duplicate_cooldown_hours: float | None = None,
    ) -> None:
        """Initialize the job with its injected collaborators.

        Args:
            job_dispatcher: Used to enqueue the actual reminder dispatch
                — either durably, for a separate worker to execute, or
                synchronously in-process when Redis is not configured
                (see ``JobDispatcher``'s docstring).
            approval_repo: Used for the broad pending-stage discovery
                query.
            request_repo: Used to resolve a stage's parent request.
            workflow_definition_repo: Used to resolve a stage's own
                pinned workflow definition.
            notification_repo: Used only for the read-only duplicate-
                reminder check — this job never writes to this
                repository directly.
            workflow_engine: The composed Workflow Engine facade, used
                to compute each stage's escalation eligibility.
            interval_seconds: The default interval this job runs at.
                Defaults to one day, matching WEDD Section 8.3's
                documented interval.
            lead_time_hours: How far before a stage's escalation
                threshold a reminder becomes due.
            duplicate_cooldown_hours: The minimum time that must have
                elapsed since a prior reminder for the same request
                before another is sent. Defaults to ``interval_seconds``
                converted to hours, so that, under normal single-instance
                operation, at most one reminder per request is sent per
                scheduled interval.
        """
        self._job_dispatcher = job_dispatcher
        self._approval_repo = approval_repo
        self._request_repo = request_repo
        self._workflow_definition_repo = workflow_definition_repo
        self._notification_repo = notification_repo
        self._workflow_engine = workflow_engine
        self._interval_seconds = interval_seconds
        self._lead_time_hours = lead_time_hours
        self._duplicate_cooldown_hours = (
            duplicate_cooldown_hours
            if duplicate_cooldown_hours is not None
            else interval_seconds / 3600.0
        )
        self._logger = logging.getLogger(f"{__name__}.ReminderJob")

    @property
    def name(self) -> str:
        """This job's stable identifier, ``"reminder_dispatch"``."""
        return "reminder_dispatch"

    @property
    def interval_seconds(self) -> int:
        """The configured interval, in seconds, this job runs at."""
        return self._interval_seconds

    def _execute(self, context: ExecutionContext) -> tuple[int, int]:
        """Discover and remind every currently due-for-reminder pending stage.

        Args:
            context: The execution context for this run.

        Returns:
            A tuple of ``(items_processed, items_failed)`` across every
            pending stage considered.
        """
        candidates = list(iter_pending_stages(self._approval_repo))
        self._logger.info(
            "Reminder dispatch considering %d pending stage(s)",
            len(candidates),
            extra={"candidate_count": len(candidates)},
        )

        # One definition cache per run — see EscalationJob's identical
        # comment/rationale.
        definition_cache: dict[UUID, WorkflowDefinition] = {}
        result = run_over_items(
            candidates,
            lambda stage: self._evaluate_and_remind_if_due(
                stage, definition_cache=definition_cache
            ),
            job_logger=self._logger,
        )
        return result.processed_count, result.failed_count

    def _evaluate_and_remind_if_due(
        self, stage: WorkflowStageRecord, *, definition_cache: dict[UUID, WorkflowDefinition]
    ) -> None:
        """Evaluate whether a single stage is due for a reminder, and send one if so.

        The escalation threshold itself is not computed via a public
        ``WorkflowEngine`` method — WEDD Section 2 assigns threshold
        computation to ``EscalationManager`` internally, and
        ``WorkflowEngine`` exposes only the boolean
        ``is_stage_escalation_eligible`` check over it, not the raw
        threshold. This job needs a lead-time window rather than a
        boolean, so it independently computes elapsed time against the
        stage's own configured ``escalation_hours`` using
        ``app.utils.datetime_utils`` — the same duration arithmetic
        ``EscalationManager`` uses, expressed at this job's own level
        rather than by reaching into the engine's internals.

        Args:
            stage: The candidate stage.
            definition_cache: This run's shared workflow-definition cache
                — see ``load_stage_context``'s own docstring.

        Raises:
            RecordNotFoundError: If the stage's request or workflow
                definition can no longer be resolved.
            StageNotFoundInDefinitionError: If the stage's own order does
                not appear in its pinned definition.
        """
        if stage.assigned_to is None:
            # A department-queue-assigned stage (WEDD Section 7.3) has no
            # single recipient to remind individually; reminders in the
            # current baseline are addressed to a specific assignee only.
            return

        stage_context = load_stage_context(
            stage,
            request_repo=self._request_repo,
            workflow_definition_repo=self._workflow_definition_repo,
            definition_cache=definition_cache,
        )
        escalation_hours = stage_context.stage_definition.escalation_hours

        already_escalation_eligible = self._workflow_engine.is_stage_escalation_eligible(
            stage.created_at, escalation_hours
        )
        if already_escalation_eligible:
            # This stage is past its threshold already; it is the
            # Escalation Check job's responsibility, not the Reminder
            # Dispatch job's, to act on it now.
            return

        elapsed_hours = seconds_between(stage.created_at, utc_now()) / 3600.0
        hours_until_threshold = escalation_hours - elapsed_hours
        is_due_for_reminder = hours_until_threshold <= self._lead_time_hours

        if not is_due_for_reminder:
            return

        if self._recently_reminded(stage=stage):
            self._logger.debug(
                "Skipping reminder for stage %s: recipient already reminded within "
                "the last %.1f hour(s).",
                stage.id,
                self._duplicate_cooldown_hours,
                extra={"stage_id": str(stage.id)},
            )
            return

        self._job_dispatcher.enqueue(
            task_type=TASK_SEND_REMINDER,
            queue_name="escalation",
            payload={
                "recipient_id": str(stage.assigned_to),
                "request_id": str(stage.request_id),
                "message": (
                    f"The stage '{stage.stage_name}' on request "
                    f"'{stage_context.request.title}' has been awaiting your decision "
                    f"since {format_iso8601(stage.created_at)} and is nearing its "
                    "escalation deadline."
                ),
            },
            priority=JobPriority.LOW,
            max_attempts=_SEND_REMINDER_MAX_ATTEMPTS,
            request_id=stage.request_id,
        )

    def _recently_reminded(self, *, stage: WorkflowStageRecord) -> bool:
        """Check whether the stage's assignee already received a reminder
        for this request within the configured cooldown window.

        Per this module's docstring, ``NotificationRepository`` exposes
        no method to filter by ``request_id`` or ``notification_type``
        directly, so this check fetches a bounded page of the
        recipient's most recent notifications and filters client-side.

        Args:
            stage: The stage being evaluated. ``stage.assigned_to`` is
                assumed non-``None`` (the only caller,
                ``_evaluate_and_remind_if_due``, already guarantees
                this).

        Returns:
            ``True`` if a ``reminder`` notification for the same
            ``request_id`` was created within the cooldown window.
        """
        assert stage.assigned_to is not None  # noqa: S101 - guaranteed by the sole caller
        page = self._notification_repo.list_for_recipient(
            stage.assigned_to, page=Page(size=_DUPLICATE_CHECK_PAGE_SIZE)
        )
        cooldown_cutoff_hours_ago = self._duplicate_cooldown_hours
        now = utc_now()
        for notification in page.items:
            if notification.notification_type is not NotificationType.REMINDER:
                continue
            if notification.request_id != stage.request_id:
                continue
            age_hours = seconds_between(notification.created_at, now) / 3600.0
            if age_hours <= cooldown_cutoff_hours_ago:
                return True
        return False
